### PR TITLE
Changes to storing images in a single pdf file.

### PR DESCRIPTION
**Pull request by projjal1**
Just work with the margins while saving the pdf file.

### CODE REVIEW

**Review by sabarishkumaran — COMMENTED** [review]
rgb.save('final_output.pdf', append=True)  ---> This appends to existing PDF 
If we make append=false it doesn't work!

Check @projjal1

**Comment by projjal1** [comment]
@sabarishkumaran  true that's why I did gave value "True".  If you give append=False it won't work.

**Comment by projjal1** [comment]
Now please merge this to the master repo.

**Comment by sabarishkumaran** [comment]
> @sabarishkumaran true that's why I did gave value "True". If you give append=False it won't work.

@projjal1 But if there is something already in PDF then we only need to overwrite it in most of the cases am I right?
Try to solve it!
and I don't have write access to this master repo!

**Comment by projjal1** [comment]
Yes, that's true. But that will not be the case. Since we are creating pdf from a blank page (ie. myfont/bg.png) and then adding generated images to successive pages of pdf. 
But if we are trying to add new pages to a pre-existing pdf file, then it will not override (it will simply add pages at the end).

**Pull request merged**
